blank_issues_enabled: false # Forces users to use your forms or links
contact_links:
  - name: ðŸ’¡  
    url: https://github.com/AptFox/harmony-frontend/discussions/new?category=feature-requests
    about: Want a new feature in Harmony? Suggest it!
  - name: ðŸ’¬ General Question
    url: https://github.com/AptFox/harmony-frontend/discussions/new?category=q-a
    about: Need help using Harmony? Ask here.